# Config description https://jekyllrb.com/docs/configuration/
permalink: :title
highlighter: rouge
description: SH blog
author:
  github: SabbathHex

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

theme: jekyll-theme-minimal
