# Config description https://jekyllrb.com/docs/configuration/
permalink: :title
highlighter: rouge
description: SH blog
author:
    github: SabbathHex
title: "~sabbathhex/blog"
plugins:
    - "jekyll-github-metadata"
collections:
    posts:
        link: "/"
    pinned_pages:
        link: "/pinned_pages"


rss_path: feed.xml
excerpt_separator: "<!--more-->"
tags_path: tags.html
